- app/build.gradle
- app/src/main/java/com/aws/amazonlocation/ui/main/MainActivity.kt
- app/src/main/java/com/aws/amazonlocation/ui/main/setting/AWSCloudInformationFragment.kt
- app/src/main/java/com/aws/amazonlocation/ui/main/signin/CloudFormationBottomSheetFragment.kt
fix(Tracking): IoT region set
fix(Auth): Remove suffix from domain field
> Remove suffix from domain and IoT region set for notification

- app/src/main/java/com/aws/amazonlocation/ui/main/MainActivity.kt
> Login management

- README.md
> Test Actions

- README.md
Reverts aws-geospatial/amazon-location-features-demo-android#15
> Revert "Test Actions"

- app/src/main/java/com/aws/amazonlocation/ui/main/MainActivity.kt
- app/src/main/java/com/aws/amazonlocation/ui/main/geofence/GeofenceUtils.kt
- app/src/main/java/com/aws/amazonlocation/ui/main/tracking/TrackingUtils.kt
- app/src/main/java/com/aws/amazonlocation/utils/AWSLocationHelper.kt
- app/src/main/java/com/aws/amazonlocation/utils/Constants.kt
- app/src/main/java/com/aws/amazonlocation/utils/DialogUtils.kt
- app/src/main/res/values-ar/string.xml
- app/src/main/res/values-de/string.xml
- app/src/main/res/values-es/string.xml
- app/src/main/res/values-fr/string.xml
- app/src/main/res/values-hi/string.xml
- app/src/main/res/values-it/string.xml
- app/src/main/res/values-iw/string.xml
- app/src/main/res/values-ja/string.xml
- app/src/main/res/values-ko/string.xml
- app/src/main/res/values-pt/string.xml
- app/src/main/res/values-zh-rCN/string.xml
- app/src/main/res/values-zh-rTW/string.xml
- app/src/main/res/values/strings.xml
*Description of changes*
fix(Tracking): Tracking sheet not opening bug fixed
fix(Simulation): Grab simulation dialog added, Analytics with grab provider not working fixed
> Tracking sheet, simulation and analytics for grab bug fixes

- app/src/main/java/com/aws/amazonlocation/utils/AWSLocationHelper.kt
ALS-1603: Prod - Android Tablet - System will give Stack corruption message when i click on search button on keyboard while searching
> Fixed Stack Corruption on Grab Search

- app/src/androidTest/java/com/aws/amazonlocation/ui/main/AnalyticsTest.kt
- app/src/main/java/com/aws/amazonlocation/ui/main/MainActivity.kt
- app/src/main/java/com/aws/amazonlocation/ui/main/explore/ExploreFragment.kt
- app/src/main/java/com/aws/amazonlocation/ui/main/region/RegionFragment.kt
- app/src/main/java/com/aws/amazonlocation/ui/main/setting/SettingFragment.kt
- app/src/main/java/com/aws/amazonlocation/ui/main/simulation/SimulationUtils.kt
- app/src/main/java/com/aws/amazonlocation/utils/AWSLocationHelper.kt
- app/src/main/java/com/aws/amazonlocation/utils/AnalyticsHelper.kt
- app/src/main/java/com/aws/amazonlocation/utils/GeneralUtils.kt
- fix(Analytics): Analytics E2E test case added
- fix(Region): Region display changes
- fix(Simulation): Simulation does not complete the second time bug fix
- fix(Auth): Click here on how to connect to AWS does not work bug fix
- fix(Simulation): Simulation should start after the map loading bug fix
> Simulation, Region, Auth bug fixes and Analytics E2E test case added

- app/src/main/java/com/aws/amazonlocation/ui/main/explore/ExploreFragment.kt
- app/src/main/java/com/aws/amazonlocation/ui/main/simulation/SimulationUtils.kt
- app/src/main/java/com/aws/amazonlocation/utils/Constants.kt
- app/src/main/java/com/aws/amazonlocation/utils/MapHelper.kt
fix(Route): Map zooms in on the destination point after switching the destination point with the starting point bug fix
fix(Simulation): User is able to see the map is a bit too much zoomed out Bug fix
fix(Route): Swap origin and destination rapid click bug fix
> [Makeen][Bug] Map zoom and swap bug fixes

- app/src/main/java/com/aws/amazonlocation/ui/main/simulation/SimulationUtils.kt
- app/src/main/java/com/aws/amazonlocation/utils/Constants.kt
- app/src/main/java/com/aws/amazonlocation/utils/MapHelper.kt
> [Makeen] [ALS-1668] Route notifications showing intermittent duplication behavior

- app/src/main/java/com/aws/amazonlocation/ui/main/tracking/TrackingUtils.kt
- app/src/main/res/layout-sw600dp-land/bottom_sheet_tracking.xml
- app/src/main/res/layout-sw600dp/bottom_sheet_tracking.xml
- app/src/main/res/layout-sw720dp-land/bottom_sheet_tracking.xml
- app/src/main/res/layout-sw720dp/bottom_sheet_tracking.xml
- app/src/main/res/layout/bottom_sheet_tracking.xml
- app/src/main/res/values/dimens.xml
- Fix (Tracking): Tracking UI bug fixes
> [Makeen] [Bug ALS-1663] Tracking UI bug fixes

- app/src/main/java/com/aws/amazonlocation/ui/main/MainActivity.kt
- app/src/main/java/com/aws/amazonlocation/utils/AWSLocationHelper.kt
- fix(Auth):  Session expired fix (unmarshal response fix)
> [Makeen] [Bug ALS-1670] Session expire fix

- app/src/main/java/com/aws/amazonlocation/ui/main/MainActivity.kt
- app/src/main/java/com/aws/amazonlocation/ui/main/geofence/GeofenceUtils.kt
- app/src/main/java/com/aws/amazonlocation/ui/main/tracking/TrackingUtils.kt
- app/src/main/res/layout-sw600dp-land/bottom_sheet_tracking.xml
- app/src/main/res/layout-sw600dp/bottom_sheet_geofence_list.xml
- app/src/main/res/layout-sw600dp/bottom_sheet_tracking.xml
- app/src/main/res/layout-sw720dp-land/bottom_sheet_tracking.xml
- app/src/main/res/layout-sw720dp/bottom_sheet_geofence_list.xml
- app/src/main/res/layout-sw720dp/bottom_sheet_tracking.xml
- app/src/main/res/layout/bottom_sheet_geofence_list.xml
- app/src/main/res/layout/bottom_sheet_tracking.xml
- Fix(Geofence): User is not able to see the last line of the Gefence UI fix
- Fix(Tracking):  The distance between the “Not tracking your device history” and the tab bar is very congested UI fix
> [Makeen] [Bug- ALS-1667] - fixed UI issue inside geofence and tracking tab

- app/src/main/java/com/aws/amazonlocation/ui/main/explore/ExploreFragment.kt
- Fix(Explore): On the selected vehicle, if API fails, the user can see the error message bug fixed.
- Fix(Explore): On swap location route options appear for walk, bicycle, and motorcycle bug fixed.
- Fix(Explore): On route option card close avoid tolls and ferries get reset bug fixed.
> [Makeen] [Bug- ALS-1660] - Route disappeared without error display and swap location fix

- .github/workflows/test-android.yml
_Description of changes:_
- Chor(Unit Test): Updated .yml file to add support for unit test report
> [Makeen] [Bug- ALS-1689] Integration of unit test cases

- app/src/main/java/com/aws/amazonlocation/ui/main/attribution/AttributionFragment.kt
- app/src/main/java/com/aws/amazonlocation/ui/main/explore/ExploreFragment.kt
- app/src/main/java/com/aws/amazonlocation/utils/Constants.kt
- Broken display on attribution bug fix
> [Makeen] [Bug- ALS-1702] Broken display on attribution bug fix

- app/src/main/java/com/aws/amazonlocation/utils/Constants.kt
- app/src/main/java/com/aws/amazonlocation/utils/GeneralUtils.kt
- IdentityPoolId validation fixes
> [Makeen] [Bug- ALS-1694] Validate IdentityPoolId bug fix 

- README.md
- extra/default-unauth-resources-template.yaml
- extra/main-cf-template.yaml
> [Makeen] Added additional details in readme

- README.md
- app/src/main/java/com/aws/amazonlocation/ui/base/BaseActivity.kt
- app/src/main/java/com/aws/amazonlocation/ui/main/MainActivity.kt
- app/src/main/java/com/aws/amazonlocation/ui/main/explore/ExploreFragment.kt
- app/src/main/java/com/aws/amazonlocation/ui/main/explore/ExploreViewModel.kt
- app/src/main/java/com/aws/amazonlocation/ui/main/simulation/SimulationUtils.kt
- app/src/main/java/com/aws/amazonlocation/utils/AWSLocationHelper.kt
- app/src/main/java/com/aws/amazonlocation/utils/BottomSheetHelper.kt
- app/src/main/java/com/aws/amazonlocation/utils/Constants.kt
- app/src/main/java/com/aws/amazonlocation/utils/GeneralUtils.kt
- app/src/main/java/com/aws/amazonlocation/utils/Units.kt
- app/src/main/res/layout/bottom_sheet_direction_search.xml
- app/src/main/res/values-ar/string.xml
- app/src/main/res/values-de/string.xml
- app/src/main/res/values-es/string.xml
- app/src/main/res/values-fr/string.xml
- app/src/main/res/values-hi/string.xml
- app/src/main/res/values-it/string.xml
- app/src/main/res/values-iw/string.xml
- app/src/main/res/values-ja/string.xml
- app/src/main/res/values-ko/string.xml
- app/src/main/res/values-pt/string.xml
- app/src/main/res/values-zh-rCN/string.xml
- app/src/main/res/values-zh-rTW/string.xml
- app/src/main/res/values/strings.xml
- scripts/translation-script/package-lock.json
- Network disconnected bug fixes
- White screen while no internet connection on the app start bug fixed
- Search direction loader, swap, error message change, and other bug fixes
- Keyboard open on search and direction sheet
- Quickly click on the map style button opens multiple sheets in the tablet bug fix
> [Bug] V2 bug fixes

- app/build.gradle
> [Bug- ALS-1735] App language change bug fix

- app/build.gradle
> Als 1735 language prod issue main

- app/build.gradle
- CF template URL update for different build types
> [Bug] CF template URL update

- scripts/translation-script/package-lock.json
There are several security dependabot issues for this package currently:
https://github.com/aws-geospatial/amazon-location-features-demo-android/security/dependabot
I ran `npm audit fix` that should address several of them.
> Fixed several vulnerabilities using `npm audit fix`

- app/src/test/java/com/aws/amazonlocation/mock/Constants.kt
- app/src/test/java/com/aws/amazonlocation/utils/generalutils/GeneralUtilsValidateLatLngTest.kt
- app/src/test/java/com/aws/amazonlocation/utils/turf/TurfMetaCoordsPointTest.kt
- app/src/test/java/com/aws/amazonlocation/utils/turf/TurfModuleTest.kt
fix: test case method and strings renamed and latitude and longitude position issue solved
> ALS-1806 Refactor method and string names and minor fixes

- app/build.gradle
- app/src/main/java/com/aws/amazonlocation/data/datasource/RemoteDataSourceImpl.kt
- app/src/main/java/com/aws/amazonlocation/ui/base/BaseActivity.kt
- app/src/main/java/com/aws/amazonlocation/ui/main/MainActivity.kt
- app/src/main/java/com/aws/amazonlocation/ui/main/explore/ExploreFragment.kt
- app/src/main/java/com/aws/amazonlocation/ui/main/region/RegionFragment.kt
- app/src/main/java/com/aws/amazonlocation/ui/main/simulation/SimulationUtils.kt
- app/src/main/java/com/aws/amazonlocation/utils/BottomSheetHelper.kt
- app/src/main/java/com/aws/amazonlocation/utils/Constants.kt
- app/src/main/java/com/aws/amazonlocation/utils/GeneralUtils.kt
- app/src/main/java/com/aws/amazonlocation/utils/analytics/AnalyticsUtils.kt
- app/src/main/java/com/aws/amazonlocation/utils/providers/LocationProvider.kt
- app/src/main/java/com/aws/amazonlocation/utils/providers/PlacesProvider.kt
- app/src/main/java/com/aws/amazonlocation/utils/providers/RoutesProvider.kt
- app/src/main/res/layout-sw600dp/bottom_sheet_direction_search.xml
- app/src/main/res/layout-sw720dp/bottom_sheet_direction_search.xml
- app/src/main/res/layout/bottom_sheet_direction_search.xml
fix: reverse geocode and direction button should not work if only data is pulled bug fixes
fix: Two bottom sheet opening fixes with code optimization
refactor: Auth SDK version update with related code changes
> ALS-1882 Auth SDK updated to latest and bug fixes

- app/src/main/java/com/aws/amazonlocation/ui/main/explore/SearchPlacesAdapter.kt
- app/src/main/java/com/aws/amazonlocation/ui/main/explore/SearchPlacesSuggestionAdapter.kt
fix: Code optimized based on PR comments
> ALS-1918 Code optimized based on PR comments

- app/src/main/java/com/aws/amazonlocation/ui/main/explore/ExploreFragment.kt
- app/src/main/java/com/aws/amazonlocation/utils/MapHelper.kt
- app/src/main/java/com/aws/amazonlocation/utils/providers/PlacesProvider.kt
fix: when the location is disabled, take the location from the centre of the map to calculate the search distance.
> ALS-1969 Location disable search fix

- app/src/androidTest/java/com/aws/amazonlocation/ui/main/ChangeMultipleDepartOptionsTest.kt
- app/src/androidTest/java/com/aws/amazonlocation/ui/main/CheckDepartOptionsTest.kt
- app/src/main/java/com/aws/amazonlocation/ui/main/explore/ExploreFragment.kt
- app/src/main/res/values/strings.xml
fix: Code optimization(string change for U-turn & method and variables name update)
<div style="display: flex; gap: 10px;">
</div>
> ALS-1820 Code optimizations

- app/src/test/java/com/aws/amazonlocation/TestUtil.kt
> ALS-1978 Removed wildcard import

- app/src/main/java/com/aws/amazonlocation/ui/main/explore/ExploreFragment.kt
> ALS-2052 Code optimization

- app/src/androidTest/java/com/aws/amazonlocation/ui/main/SimulationStartTrackingHistoryLoggedTest.kt
- app/src/androidTest/java/com/aws/amazonlocation/ui/main/SimulationStopTrackingHistoryLoggedTest.kt
- app/src/main/java/com/aws/amazonlocation/ui/main/attribution/AttributionFragment.kt
- app/src/main/java/com/aws/amazonlocation/ui/main/map_style/MapStyleBottomSheetFragment.kt
- app/src/main/java/com/aws/amazonlocation/ui/main/map_style/MapStyleChangeListener.kt
- app/src/main/java/com/aws/amazonlocation/ui/main/map_style/MapStyleFragment.kt
- app/src/main/java/com/aws/amazonlocation/ui/main/map_style/MapStyleViewModel.kt
- app/src/main/java/com/aws/amazonlocation/ui/main/map_style/SettingMapStyleAdapter.kt
- app/src/main/java/com/aws/amazonlocation/ui/main/more/AboutFragment.kt
- app/src/main/java/com/aws/amazonlocation/ui/main/region/RegionFragment.kt
- app/src/main/java/com/aws/amazonlocation/ui/main/route_option/RouteOptionFragment.kt
- app/src/main/java/com/aws/amazonlocation/ui/main/setting/AWSCloudInformationFragment.kt
- app/src/main/java/com/aws/amazonlocation/ui/main/setting/SettingFragment.kt
- app/src/main/java/com/aws/amazonlocation/ui/main/simulation/SimulationBottomSheetFragment.kt
- app/src/main/java/com/aws/amazonlocation/ui/main/simulation/SimulationListAdapter.kt
- app/src/main/java/com/aws/amazonlocation/ui/main/simulation/SimulationTrackingListAdapter.kt
- app/src/main/java/com/aws/amazonlocation/ui/main/simulation/SimulationUtils.kt
- app/src/main/java/com/aws/amazonlocation/ui/main/simulation/SimulationViewModel.kt
- app/src/main/java/com/aws/amazonlocation/ui/main/unit_system/UnitSystemFragment.kt
- app/src/test/java/com/aws/amazonlocation/viewmodel/mapstyle/MapStyleVMMapListData.kt
- app/src/test/java/com/aws/amazonlocation/viewmodel/mapstyle/MapStyleVMSetLanguageListData.kt
- app/src/test/java/com/aws/amazonlocation/viewmodel/mapstyle/MapStyleVMSetPoliticalListData.kt
- app/src/test/java/com/aws/amazonlocation/viewmodel/simulation/SimulationVMGetGeofenceList.kt
fix: code optimization with ktlint for settings and simulation module
> ALS-1978 Code optimization with ktlint for settings and simulation module

- app/src/main/java/com/aws/amazonlocation/ui/main/geofence/GeofenceUtils.kt
- app/src/main/java/com/aws/amazonlocation/ui/main/geofence/GeofenceViewModel.kt
- app/src/main/java/com/aws/amazonlocation/ui/main/signin/CloudFormationBottomSheetFragment.kt
- app/src/main/java/com/aws/amazonlocation/ui/main/signin/CustomSpinnerAdapter.kt
- app/src/main/java/com/aws/amazonlocation/ui/main/signin/SignInConnectedBottomSheetFragment.kt
- app/src/main/java/com/aws/amazonlocation/ui/main/signin/SignInRequiredBottomSheetFragment.kt
- app/src/main/java/com/aws/amazonlocation/ui/main/signin/SignInViewModel.kt
- app/src/main/java/com/aws/amazonlocation/ui/main/tracking/TrackingHistoryAdapter.kt
- app/src/main/java/com/aws/amazonlocation/ui/main/tracking/TrackingUtils.kt
- app/src/main/java/com/aws/amazonlocation/ui/main/tracking/TrackingViewModel.kt
- app/src/test/java/com/aws/amazonlocation/viewmodel/tracking/SignInViewModelTest.kt
- app/src/test/java/com/aws/amazonlocation/viewmodel/tracking/TrackingVMBatchUpdateDevicePositionTest.kt
- app/src/test/java/com/aws/amazonlocation/viewmodel/tracking/TrackingVMDeleteLocationHistory.kt
- app/src/test/java/com/aws/amazonlocation/viewmodel/tracking/TrackingVMGetGeofenceList.kt
- app/src/test/java/com/aws/amazonlocation/viewmodel/tracking/TrackingVMGetLocationHistory.kt
- app/src/test/java/com/aws/amazonlocation/viewmodel/tracking/TrackingVMGetLocationHistoryToday.kt
fix: code optimization with ktlint on geofence, tracking and sign-in module
> ALS-1978 code optimization with ktlint on geofence, tracking and sign-in module

- app/src/main/java/com/aws/amazonlocation/ui/main/geofence/GeofenceUtils.kt
- app/src/main/java/com/aws/amazonlocation/ui/main/geofence/GeofenceViewModel.kt
- app/src/main/java/com/aws/amazonlocation/ui/main/signin/CloudFormationBottomSheetFragment.kt
- app/src/main/java/com/aws/amazonlocation/ui/main/signin/CustomSpinnerAdapter.kt
- app/src/main/java/com/aws/amazonlocation/ui/main/signin/SignInConnectedBottomSheetFragment.kt
- app/src/main/java/com/aws/amazonlocation/ui/main/signin/SignInRequiredBottomSheetFragment.kt
- app/src/main/java/com/aws/amazonlocation/ui/main/signin/SignInViewModel.kt
- app/src/main/java/com/aws/amazonlocation/ui/main/tracking/TrackingHistoryAdapter.kt
- app/src/main/java/com/aws/amazonlocation/ui/main/tracking/TrackingUtils.kt
- app/src/main/java/com/aws/amazonlocation/ui/main/tracking/TrackingViewModel.kt
- app/src/test/java/com/aws/amazonlocation/viewmodel/tracking/SignInViewModelTest.kt
- app/src/test/java/com/aws/amazonlocation/viewmodel/tracking/TrackingVMBatchUpdateDevicePositionTest.kt
- app/src/test/java/com/aws/amazonlocation/viewmodel/tracking/TrackingVMDeleteLocationHistory.kt
- app/src/test/java/com/aws/amazonlocation/viewmodel/tracking/TrackingVMGetGeofenceList.kt
- app/src/test/java/com/aws/amazonlocation/viewmodel/tracking/TrackingVMGetLocationHistory.kt
- app/src/test/java/com/aws/amazonlocation/viewmodel/tracking/TrackingVMGetLocationHistoryToday.kt
fix: code optimization with ktlint on geofence, tracking and sign-in module
> ALS-1978 code optimization with ktlint on geofence, tracking and sign-in modulea

- .github/workflows/build-android.yml
- .github/workflows/ktlint-android.yml
- .github/workflows/lint-android.yml
- .github/workflows/test-android-e2e.yml
- .github/workflows/test-android.yml
Address code scan workflow permissions result
Reduce github workflow permissions to read contents and write actions to support artifact upload.
> fix(github): reduced workflow permission scope
